apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test-auth
  template:
    metadata:
      labels:
        app: jenkins-test-auth
    spec:
      containers:
        - name: jenkins-test-auth
          image: ddarahakit/jenkins-test:0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret